server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db_lagou?useSSL=false&useUnicode=true&characterEncoding=UTF-8
  redis:
    database: 0
    host: 192.168.213.128
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 3000ms
        max-idle: 8
        min-idle: 2
    timeout: 3000ms
  resources:
    static-locations: classpath:/static/
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
#  打印SQL
logging:
  level:
    com.wzx.lagou.repository.auto: off